<?php

namespace TechnoBureau\mezzioPDOAuth\Repository;

/**
 * AuthUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthUserRepository extends \Doctrine\ORM\EntityRepository
{
}
